---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitlab-ce
  name: gitlab-ce
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 4430
      targetPort: 443
      nodePort: 30230
      name: 'gitlab-ce-port-443'
    - port: 8000
      targetPort: 80
      nodePort: 30231
      name: 'gitlab-ce-port-80'
    - port: 2200
      targetPort: 22
      nodePort: 30232
      name: 'gitlab-ce-port-22'
  selector:
    app: gitlab-ce

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-ce
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab-ce
    spec:
      containers:
        - name: gitlab-ce
          image: gitlab/gitlab-ce:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
          volumeMounts:
            - mountPath: /etc/gitlab
              name: gitlab-ce-etc
            - mountPath: /var/log/gitlab
              name: gitlab-ce-log
            - mountPath: /var/opt/gitlab
              name: gitlab-ce-data
      volumes:
        - name: gitlab-ce-etc
          hostPath:
            path: /data/default/gitlab/config
        - name: gitlab-ce-log
          hostPath:
            path: /data/default/gitlab/logs
        - name: gitlab-ce-data
          hostPath:
            path: /data/default/gitlab/data